name: Build and push image

on:
  workflow_dispatch:
    inputs:
      phpVersion:
        description: 'The PHP version to compile'
        required: true
        type: string

env:
  TEST_TAG: alekitto/php-fpm:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          build-args: |
            PHP_VERSION=${{ inputs.phpVersion }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ env.TEST_TAG }}

      -
        name: Test
        run: |
          docker run --rm ${{ env.TEST_TAG }} php -v

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          load: true
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: |
            PHP_VERSION=${{ inputs.phpVersion }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: alekitto/php-fpm:${{ inputs.phpVersion }}

